### ISSUE TITLE
SSKR output as ByteWords

### ISSUE THREAD

**Issue by aido** [BlockchainCommons/seedtool-cli-rust#1]
Hi,

I can use `seedtool` to encode a BIP39 mnemonic as SSKR:

```bash
aido@dev01:~/git/seedtool-cli-rust$ seedtool --in hex "7daa851251002874e1a1995f0897e6b1" --out bip39
laundry feature duty pear action denial make creek gallery dwarf whale glove
aido@dev01:~/git/seedtool-cli-rust$ seedtool --in bip39 "laundry feature duty pear action denial make creek gallery dwarf whale glove" --out sskr --groups=2-of-3
ur:envelope/lftansfwlrhdcerhisrkvwflotpldrgtfmwzykrpcwkkqdbbjlimterfienthedaihlbqzgsntahdttpfgmnvdftlkgelpvegdptjsbdsfcmjnnsswkpmnrhtlrkpapaknhddatansfphdcxwtfyhlcpckytwecsfphltkhyvtfljkurbdatlbnsbynlgmtitkfpcwftonaomtlfoyamtpsotantkphddaldytaeadaeaspkfdfxfzsejzsflbpkuocklgonfygufwytsogliycytywttpcywmzocxrnhklbmytdjsry
ur:envelope/lftansfwlrhdcerhisrkvwflotpldrgtfmwzykrpcwkkqdbbjlimterfienthedaihlbqzgsntahdttpfgmnvdftlkgelpvegdptjsbdsfcmjnnsswkpmnrhtlrkpapaknhddatansfphdcxwtfyhlcpckytwecsfphltkhyvtfljkurbdatlbnsbynlgmtitkfpcwftonaomtlfoyamtpsotantkphddaldytaeadaddalrfdykcnneoskickveemvdynuytiyafhbasbdaqzltutrkdmfpsplyimmolrtapmbdcxto
ur:envelope/lftansfwlrhdcerhisrkvwflotpldrgtfmwzykrpcwkkqdbbjlimterfienthedaihlbqzgsntahdttpfgmnvdftlkgelpvegdptjsbdsfcmjnnsswkpmnrhtlrkpapaknhddatansfphdcxwtfyhlcpckytwecsfphltkhyvtfljkurbdatlbnsbynlgmtitkfpcwftonaomtlfoyamtpsotantkphddaldytaeadaogyynfdeelnkivyreryenbyylkghkktckrobnsnmktafrswiydlpspmbsqzvayaderdtpbdca
```

Great!

But the output is in UR format.. How may I get the output as ByteWords in the form:
```
tuna next keep gyro gear runs body acid able film nail barn cost aqua epic veto quad fern jump buzz epic slot frog apex taxi grim fern twin leaf
tuna next keep gyro gear runs body acid acid barn luau omit navy keep also omit data wave aunt redo toil miss tent redo bias fuel work king kick
tuna next keep gyro gear runs body acid also heat ruby gala beta visa help horn liar limp monk gush waxy into junk jolt keep lion leaf ruby purr
```

I understand that seedtool-cli-rust is currently a pre-release but if this functionality is not available is it planned to be added?

**Comment by ChristopherA** [comment]
@aido Yes, this rust release really should have been labeled not just a pre-release, but a preview, as it focuses mostly in using envelope with SSKR to enable things like descriptors and other key metadata to be included. 

The team had a long call yesterday about what legacy features from the original seedtool-cli we need to support. We are committed to READ everything the the old seed tool created, but the harder question is what defaults we should support going forward, and what legacy output to continue to offer. The new envelope SSKR format will be larger, and thus less practical to use bytewords with, but in the UR form will work great with the upcoming CSR (collaborative key recovery) services we are working with multiple companies to make available as an open alternative to Ledger's social recovery.

We'd like to understand the need of your community — it sounds like you chose SSKR 1.0 because SLIP39 and other Shamir formats don't round-trip to with BIP39 words. But we've also not had as widespread adoption of it by other wallets as we hoped. Is continuing to support the minimal SSKR (seed-only, no metadata) essential for your use cases?

We'd be glad to schedule a dialogue directly with you, or if you can make the next Gordian Developer meeting on Wednesday July 10th at 10am PDT, we can add this discussion to the agenda.

**Comment by aido** [comment]
Hi @ChristopherA,


> it sounds like you chose SSKR 1.0 because SLIP39 and other Shamir formats don't round-trip to with BIP39 words

Yes, you are correct. Since accessing the seed directly through the API on Ledger hardware devices is rightly not possible, I needed another method for the Ledger app-seed-tool app to obtain the seed. The solution was to ask the user to input their BIP39 phrase and then confirm that the phrase matches the on-device seed. This functionality is an exact replica of the existing Ledger Recovery Check app. We then use that BIP39 phrase to generate the SSKR shares. Therefore, the BIP39 <-> SSKR roundtrip is essential to how the app operates.


> Is continuing to support the minimal SSKR (seed-only, no metadata) essential for your use cases?

Up to this point, the Ledger app-seed-tool app has been in a lengthy testing phase. During testing, comparing the app's output with the output of seedtool CLI has been a very convenient way to verify correct operation. While it would be nice if that functionality were still available in seedtool CLI, it is not essential now that testing of app-seed-tool is more or less complete. However, it remains crucial that minimal SSKR output format is supported by the SSKR standard itself. The app closely follows the standard as described in the latest verson of [BCR-0011](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md), specifically the minimal SSKR ByteWord output described and using CBOR Tag 6.40309.

Additionally, due to the screen size and input methods of small Ledger Nano devices, ByteWords are the preferred form of input and output over UR. However, with the new Ledger Stax devices coming soon, the much larger screen gives the potential to expand into UR output, QR codes, etc.


> But we've also not had as widespread adoption of it by other wallets as we hoped.

Two of the biggest manufacturers of hardware wallets are Ledger and Trezor. SatoshiLabs, the makers of Trezor wallets, were never going to adopt the SSKR standard in favor of their own SLIP-39 standard. However, compared to Trezor's estimated > 1.5 million devices, Ledger seems to have a much larger market share with an estimated > 6 million devices in the wild. While the app-seed-tool Ledger app has been in testing for a long time, I think we are very close to a general release. The app is already available to the general public for installation and testing by enabling a developer option in the Ledger Live app. I am pushing for a more general release, which hopefully will happen very soon.

So, I think having SSKR available to more than 6 million hardware devices would be far from "_not having widespread adoption_"; quite the opposite. Also, if/when the big player Ledger release an app using SSKR it may give SSKR more traction and encourage other wallet manufactures to follow suit.

**Comment by ChristopherA** [comment]
@aido Thanks for your detailed feedback. We are working on next revision of seedtool-cli-rust over the next week.

**Comment by ChristopherA** [comment]
@aido Check out this version https://github.com/BlockchainCommons/seedtool-cli-rust/commit/31882bfbec6a33ff039965ca3829fd66fc29907f and see if it meets your requirements.

**Comment by aido** [comment]
Wow! That was fast.

I just did a quick test and the output exactly meets my requirements. 

Thank you very much for the rapid response.

**Comment by ChristopherA** [comment]
@aido Great to hear. Can we close this issue?

BTW, I don't think it applies to you, but it might for @seedhammer, note that as of this version you are using the seed-only version the SSKR format, and are using UR encoding, that `ur:crypto-seed` is deprecated in favor of the shorter `ur:sskr`. The new rust`seedtool` will still will accept the old UR, but only output the new.

**Comment by shannona** [comment]
@aido we have our next Gordian Developer meeting coming up on July 10th (10am PDT) and would love to have you there. 

You can sign up either for a Signal or email announcements-only list to get the notifications & link to the Zoom room prior to the meeting:
https://www.blockchaincommons.com/subscribe/

Alternatively, feel free to drop me a line at: shannon.appelcline@gmail.com

Also, would you be interested in presenting on your work at this or a future meeting?
