### ISSUE TITLE
Card Inputs Produce Different Outputs on iOS & Rust Seedtools

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/seedtool-cli-rust#2]
Generated cards in iOS.

Got the seed:
```
8c5d0d97896be66dd9fec40826c9ab28
```
Shared my card-gen over to the Rust CLI, got:
```
$ seedtool -i cards 7htdad5s7s2d9d6djc8c9s4s7dks7cahth5c7hkd6d5dad
e403721f42bf14cefc4431ef8510a08b
```

**Comment by wolfmcnally** [comment]
I have determined that the iOS app was not using the correct method.
[This commit](https://github.com/BlockchainCommons/GordianSeedTool-iOS/commit/76cc56f6d83f4e91669e4b586e603710d8326322) fixes the problem.
