### ISSUE TITLE
Seed Envelopes not readable by Gordian Seedtool (iOS)

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/seedtool-cli-rust#7]
Here's an example envelope:

```
% seedtool -i hex 59f2293a5bce7d4de59e71b4207ac5d2 -o envelope 
ur:envelope/lftpsogdhkwzdtfthptokigtvwnnjsqzcxknsktdoyadcsspgmgreefy
```

Here's that Envelope in Gordian Seedtool iOS:

![7573C189-1FC7-45BB-86F3-9EF1A8C06C11_1_102_o](https://github.com/BlockchainCommons/seedtool-cli-rust/assets/1110886/9bb90855-c0d3-4c3e-bb61-5ff56fbef861)

**Comment by wolfmcnally** [comment]
This appears to have been a build issue with resolving the correct versions of included libraries. Should be fixed in the next release.
